plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-slate

title: "Coding FreeRun"
description: "Artificial Intelligence"

url                      : https://codingfreerun.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/LiveCoding" # the subpath of your site, e.g. "/blog"
    
# Reading Files
include:
  - .htaccess
  - _pages
  - files

